In [1]:
## Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
## Importing the OS and JSON Modules
import os,json

In [2]:
df = pd.read_csv('C:/Users/fid24/downloads/superhero_powers - superhero_powers.csv')
df.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [3]:
dfinfo = pd.read_csv('C:/Users/fid24/downloads/superhero_info - superhero_info.csv')
dfinfo.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [4]:
dfinfo[['Hero','Publisher']] = dfinfo['Hero|Publisher'].str.split('|',expand=True)
dfinfo.head(2)

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics

In [5]:
dfinfo = dfinfo.drop(columns=['Hero|Publisher'])
dfinfo.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics

In [6]:
meas = dfinfo.loc[0,"Measurements"]
print(type(meas))
meas

<class 'str'>

"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"

In [7]:
meas = meas.replace("'",'"')
meas

'{"Height": "203.0 cm", "Weight": "441.0 kg"}'

In [8]:
fixed_meas = json.loads(meas)
print(type(fixed_meas))
fixed_meas

<class 'dict'>

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

In [9]:
## use .str.replace to replace all single quotes
dfinfo['Measurements'] = dfinfo['Measurements'].str.replace("'",'"')
## Apply the json.loads to the full column
dfinfo['Measurements'] = dfinfo['Measurements'].apply(json.loads)
dfinfo['Measurements'].head()

0    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1     {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2     {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4    {'Height': '193.0 cm', 'Weight': '122.0 kg'}
Name: Measurements, dtype: object

In [10]:
height_weight = dfinfo['Measurements'].apply(pd.Series)
height_weight

       Height    Weight
0    203.0 cm  441.0 kg
1    191.0 cm   65.0 kg
2    185.0 cm   90.0 kg
3    203.0 cm  441.0 kg
4    193.0 cm  122.0 kg
..        ...       ...
458  183.0 cm   83.0 kg
459  165.0 cm   52.0 kg
460   66.0 cm   17.0 kg
461  170.0 cm   57.0 kg
462  185.0 cm   81.0 kg

[463 rows x 2 columns]

In [11]:
dfinfo = pd.concat((dfinfo, height_weight), axis = 1)
dfinfo.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics,203.0 cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg

In [12]:
dfinfo['Height'].str.split(' ',expand=True)

         0   1
0    203.0  cm
1    191.0  cm
2    185.0  cm
3    203.0  cm
4    193.0  cm
..     ...  ..
458  183.0  cm
459  165.0  cm
460   66.0  cm
461  170.0  cm
462  185.0  cm

[463 rows x 2 columns]

In [13]:
dfinfo[['Height_in_CM','cm']] = dfinfo['Height'].str.split(' ',expand=True)
dfinfo.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher,Height,Weight,Height_in_CM,cm
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics,203.0 cm,441.0 kg,203.0,cm
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg,191.0,cm

In [14]:
dfinfo['Weight'].str.split(' ',expand=True)

         0   1
0    441.0  kg
1     65.0  kg
2     90.0  kg
3    441.0  kg
4    122.0  kg
..     ...  ..
458   83.0  kg
459   52.0  kg
460   17.0  kg
461   57.0  kg
462   81.0  kg

[463 rows x 2 columns]

In [15]:
dfinfo[['Weight_in_KG','kg']] = dfinfo['Weight'].str.split(' ',expand=True)
dfinfo.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher,Height,Weight,Height_in_CM,cm,Weight_in_KG,kg
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics,203.0 cm,441.0 kg,203.0,cm,441.0,kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg,191.0,cm,65.0,kg

In [16]:
dfinfo = dfinfo.drop(columns=['Measurements','cm','kg','Height','Weight'])
dfinfo.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height_in_CM,Weight_in_KG
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0

In [17]:
dfinfo['Height_in_CM'] = dfinfo['Height_in_CM'].astype(float)

In [18]:
dfinfo['Weight_in_KG'] = dfinfo['Weight_in_KG'].astype(float)

In [19]:
dfinfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gender        463 non-null    object
 1   Race          463 non-null    object
 2   Alignment     463 non-null    object
 3   Hair color    463 non-null    object
 4   Eye color     463 non-null    object
 5   Skin color    463 non-null    object
 6   Hero          463 non-null    object
 7   Publisher     463 non-null    object
 8   Height_in_CM  463 non-null    float64
 9   Weight_in_KG  463 non-null    float64
dtypes: float64(2), object(8)
memory usage: 36.3+ KB

In [20]:
df['Powers'] = df['Powers'].replace(['100 kg',], '100kg')

In [21]:
df['Powers'] = df['Powers'].replace(['52.5 cm',], '52.5cm')

In [22]:
df.loc[2,'Powers']

'Agility,Accelerated Healing,Cold Resistance,Durability,Underwater breathing,Marksmanship,Weapons Master,Longevity,Intelligence,Super Strength,Telepathy,Stamina,Immortality,Reflexes,Enhanced Sight,Sub-Mariner'

In [23]:
df['Powers'].value_counts()

Intelligence                                                                                                                                                                                                                                                         8
Durability,Super Strength                                                                                                                                                                                                                                            5
Agility,Stealth,Marksmanship,Weapons Master,Stamina                                                                                                                                                                                                                  4
Marksmanship                                                                                                                                                                                                                                                         4
Teleportation                                                                                                                                                                                                                                                        4
                                                                                                                                                                                                                                                                    ..
Accelerated Healing,Flight,Telepathy,Energy Blasts,Teleportation,Telekinesis,Astral Projection,Psionic Powers,Mind Blast,Regeneration,Illusions,Resurrection                                                                                                         1
Flight,Telepathy,Animal Oriented Powers,Gliding                                                                                                                                                                                                                      1
Accelerated Healing,Durability,Energy Absorption,Flight,Super Strength,Telepathy,Energy Blasts,Size Changing,Super Speed,Darkforce Manipulation,Enhanced Senses,Phasing,Invulnerability,Self-Sustenance,Gravity Control,Energy Manipulation,Time Travel,Illusions    1
Agility,Accelerated Healing,Super Strength,Super Speed,Animal Oriented Powers,Enhanced Senses,Jump,Reflexes,Natural Weapons                                                                                                                                          1
Super Speed,Intangibility,Time Travel,Time Manipulation                                                                                                                                                                                                              1
Name: Powers, Length: 608, dtype: int64

In [24]:
x = df['Powers'].str.split(',',expand=False)
x

0        [Agility, Super Strength, Stamina, Super Speed]
1      [Accelerated Healing, Durability, Longevity, S...
2      [Agility, Accelerated Healing, Cold Resistance...
3                                   [Lantern Power Ring]
4      [Accelerated Healing, Intelligence, Super Stre...
                             ...
662               [Flight, Energy Blasts, Size Changing]
663    [Cold Resistance, Durability, Longevity, Super...
664    [Agility, Stealth, Danger Sense, Marksmanship,...
665    [Cryokinesis, Telepathy, Magic, Fire Control, ...
666    [Super Speed, Intangibility, Time Travel, Time...
Name: Powers, Length: 667, dtype: object

In [25]:
exploded = x.explode()

In [26]:
exploded

0                  Agility
0           Super Strength
0                  Stamina
0              Super Speed
1      Accelerated Healing
              ...
665        Weather Control
666            Super Speed
666          Intangibility
666            Time Travel
666      Time Manipulation
Name: Powers, Length: 5874, dtype: object

In [28]:
power_list = exploded.unique()

In [30]:
power = power_list[0]

In [31]:
df['Powers'].str.contains(power)

0       True
1      False
2       True
3      False
4      False
       ...
662    False
663    False
664     True
665    False
666    False
Name: Powers, Length: 667, dtype: bool

In [32]:
df[power] = df['Powers'].str.contains(power)
df

,hero_names,Powers,Agility
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",True
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",False
2,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...",True
3,Abin Sur,Lantern Power Ring,False
4,Abomination,"Accelerated Healing,Intelligence,Super Strengt...",False
...,...,...,...
662,Yellowjacket II,"Flight,Energy Blasts,Size Changing",False
663,Ymir,"Cold Resistance,Durability,Longevity,Super Str...",False
664,Yoda,"Agility,Stealth,Danger Sense,Marksmanship,Weap...",True
665,Zatanna,"Cryokinesis,Telepathy,Magic,Fire Control,Proba...",False
666,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",False

In [35]:
for power in power_list:
    df[power] = df['Powers'].str.contains(power).copy()

In [36]:
df

,hero_names,Powers,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,Camouflage,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",True,True,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",False,True,True,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...",True,True,True,False,True,True,True,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,Lantern Power Ring,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,"Accelerated Healing,Intelligence,Super Strengt...",False,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,Yellowjacket II,"Flight,Energy Blasts,Size Changing",False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
663,Ymir,"Cold Resistance,Durability,Longevity,Super Str...",False,True,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
664,Yoda,"Agility,Stealth,Danger Sense,Marksmanship,Weap...",True,False,True,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
665,Zatanna,"Cryokinesis,Telepathy,Magic,Fire Control,Proba...",False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
666,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
exploded = df.explode('Powers')

In [ ]:
cols_to_make = exploded['Powers'].dropna().unique()
cols_to_make

In [ ]:
for col in cols_to_make:
    df[col] = df['Powers'].str.contains(col)
df.head()

In [ ]:
df = df.drop(columns=['Powers'])
df.head(2)

In [ ]:
final_df = pd.merge(dfinfo, df, left_on='Hero', right_on='hero_names', how='inner')
final_df.head(3)

### Compare the average weight of super powers who have Super Speed to those who do not.
### What is the average height of heroes for each publisher?

i dont know how to get an answer for the first question at all, super speed is in so many columns and i guess i dont understand pandas well enough.
as for the second question i think i could split the Height column again so i can use a group by with the mean aggregate but i dont think thats the right way to do it.